---
title: "CodeBook"
---
## Variable Descriptions
Activity: Activity performed by Each person wearing a smartphone (Samsung Galaxy S II) on the wais  
          1-LAYING  
          2-SITTING  
          3-STANDING  
          4-WALKING  
          5-WALKING_DOWNSTAIRS  
          6-WALKING_UPSTAIRS  

Subject: the gorup ID of Volunteers
        number
            1:30

Averag of:XXX
  Mean value of variable XXX per each activity and each subject, 
  't' to indicate the time domain 
  'f' to indicate frequency domain signals 
  Acc to indicate accelerometer
  Gyro to indicate Gyroscope
  XYZ to indicate 3-axial
  mean(): Mean value
  std(): Standard deviation
        
        averag of:tBodyAcc-mean()-X
        averag of:tBodyAcc-mean()-Y
        averag of:tBodyAcc-mean()-Z
        averag of:tBodyAcc-std()-X
        averag of:tBodyAcc-std()-Y
        averag of:tBodyAcc-std()-Z
        averag of:tGravityAcc-mean()-X
        averag of:tGravityAcc-mean()-Y
        averag of:tGravityAcc-mean()-Z
        averag of:tGravityAcc-std()-X
        averag of:tGravityAcc-std()-Y
        averag of:tGravityAcc-std()-Z
        averag of:tBodyAccJerk-mean()-X
        averag of:tBodyAccJerk-mean()-Y
        averag of:tBodyAccJerk-mean()-Z
        averag of:tBodyAccJerk-std()-X
        averag of:tBodyAccJerk-std()-Y
        averag of:tBodyAccJerk-std()-Z
        averag of:tBodyGyro-mean()-X
        averag of:tBodyGyro-mean()-Y
        averag of:tBodyGyro-mean()-Z
        averag of:tBodyGyro-std()-X
        averag of:tBodyGyro-std()-Y
        averag of:tBodyGyro-std()-Z
        averag of:tBodyGyroJerk-mean()-X
        averag of:tBodyGyroJerk-mean()-Y
        averag of:tBodyGyroJerk-mean()-Z
        averag of:tBodyGyroJerk-std()-X
        averag of:tBodyGyroJerk-std()-Y
        averag of:tBodyGyroJerk-std()-Z
        averag of:tBodyAccMag-mean()
        averag of:tBodyAccMag-std()
        averag of:tGravityAccMag-mean()
        averag of:tGravityAccMag-std()
        averag of:tBodyAccJerkMag-mean()
        averag of:tBodyAccJerkMag-std()
        averag of:tBodyGyroMag-mean()
        averag of:tBodyGyroMag-std()
        averag of:tBodyGyroJerkMag-mean()
        averag of:tBodyGyroJerkMag-std()
        averag of:fBodyAcc-mean()-X
        averag of:fBodyAcc-mean()-Y
        averag of:fBodyAcc-mean()-Z
        averag of:fBodyAcc-std()-X
        averag of:fBodyAcc-std()-Y
        averag of:fBodyAcc-std()-Z
        averag of:fBodyAcc-meanFreq()-X
        averag of:fBodyAcc-meanFreq()-Y
        averag of:fBodyAcc-meanFreq()-Z
        averag of:fBodyAccJerk-mean()-X
        averag of:fBodyAccJerk-mean()-Y
        averag of:fBodyAccJerk-mean()-Z
        averag of:fBodyAccJerk-std()-X
        averag of:fBodyAccJerk-std()-Y
        averag of:fBodyAccJerk-std()-Z
        averag of:fBodyAccJerk-meanFreq()-X
        averag of:fBodyAccJerk-meanFreq()-Y
        averag of:fBodyAccJerk-meanFreq()-Z
        averag of:fBodyGyro-mean()-X
        averag of:fBodyGyro-mean()-Y
        averag of:fBodyGyro-mean()-Z
        averag of:fBodyGyro-std()-X
        averag of:fBodyGyro-std()-Y
        averag of:fBodyGyro-std()-Z
        averag of:fBodyGyro-meanFreq()-X
        averag of:fBodyGyro-meanFreq()-Y
        averag of:fBodyGyro-meanFreq()-Z
        averag of:fBodyAccMag-mean()
        averag of:fBodyAccMag-std()
        averag of:fBodyAccMag-meanFreq()
        averag of:fBodyBodyAccJerkMag-mean()
        averag of:fBodyBodyAccJerkMag-std()
        averag of:fBodyBodyAccJerkMag-meanFreq()
        averag of:fBodyBodyGyroMag-mean()
        averag of:fBodyBodyGyroMag-std()
        averag of:fBodyBodyGyroMag-meanFreq()
        averag of:fBodyBodyGyroJerkMag-mean()
        averag of:fBodyBodyGyroJerkMag-std()
        averag of:fBodyBodyGyroJerkMag-meanFreq()
        averag of:angle(tBodyAccMean,gravity)
        averag of:angle(tBodyAccJerkMean),gravityMean)
        averag of:angle(tBodyGyroMean,gravityMean)
        averag of:angle(tBodyGyroJerkMean,gravityMean)
        averag of:angle(X,gravityMean)
        averag of:angle(Y,gravityMean)
        averag of:angle(Z,gravityMean)
